trigger:
- master  # Trigger on master branch

pool:
  name: 'MySelfHostedPool'  # Use your self-hosted agent pool

steps:
# Use Python 3.x
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Install dependencies from requirements.txt
- script: |
    python -m venv env  # Create a virtual environment
    source env/bin/activate
    pip install -r requirements.txt  # Install dependencies
  displayName: 'Install Python Dependencies'

# Run the Python script (model.py)
- script: |
    source env/bin/activate
    python src/model.py  # Path to your Python script
  displayName: 'Run Machine Learning Model'

# Completion time
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Pipeline completed successfully at $(date)"'
  displayName: 'Completion Time'
