trigger:
- master  # Pipeline triggers when there’s a push to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu VM

steps:
# Use the correct Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Install dependencies from requirements.txt
- script: |
    python -m venv env  # Create a virtual environment
    source env/bin/activate
    pip install -r requirements.txt  # Install dependencies
  displayName: 'Install Python Dependencies'

# Run the Python script (model.py)
- script: |
    source env/bin/activate
    python src/model.py  # Make sure the path matches where your Python script is
  displayName: 'Run Machine Learning Model'

# Optional: Output something on success
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Pipeline completed successfully at $(date)"'
  displayName: 'Completion Time'
